version: '1'
services:
    web:
        image: evdev3/tweet-daily-quote
        env_file:
            - ./config/.env
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
